### ISSUE TITLE
How to set MaxTimeoutInSeconds to 9999

### ISSUE THREAD

**Issue by awtkeithlin** [berhir/AspNetCore.SpaYarp#12]
angular build is slow may be take 3 min
how to set MaxTimeoutInSeconds ?Thx  is SpaProxyTimeoutInSeconds?
and in sourcecode where is the nuget package:  Yarp.ReverseProxy.Forwarder

**Comment by awtkeithlin** [comment]
okay SpaProxyTimeoutInSeconds is work but what is the Yarp.ReverseProxy.Forwarder?

**Comment by berhir** [comment]
What exactly is your question or what do you want to achieve? This package uses "Direct Forwarding" as described in the [YARP documentation](https://microsoft.github.io/reverse-proxy/articles/direct-forwarding.html).

The forwarder is used in the `IEndpointRouteBuilderExtensions.cs` file.
