### ISSUE TITLE
Any guideline if index page is a server side Razor page?

### ISSUE THREAD

**Issue by rmeshksar** [berhir/AspNetCore.SpaYarp#13]
Hi,
In our ASP.NET/Angular application we are not using index.html, rather we do have index.cshtml Razor page and in the program.cs file we have this as very last setting:

```csharp
app.MapFallbackToController("Index", "Home");
```

and we add references to the generated JavaScript file hard-coded in the index.cshtml file:
```html
    <script src="~/dist/runtime.js" asp-append-version="true"></script>
    <script src="~/dist/polyfills.js" asp-append-version="true"></script>
    <script src="~/dist/main.js" asp-append-version="true"></script>
    <script src="~/dist/vendor.js" asp-append-version="true"></script>
```

Still we want to take advantage of hot module reloading the Angular/Webpack provide.

Do you have any recommendation?

**Comment by berhir** [comment]
Hi, it shouldn't make any difference if you use an index.html file or an index.cshtml file.

If you want to forward only requests starting with a specific path (in your case `/dist`), you can specify it in your project file: `<SpaPublicPath>/dist</SpaPublicPath>`. Please take a look at the readme for more details on how to add the configuration.
