### ISSUE TITLE
Using PublicPath to check if Spa Client server is running

### ISSUE THREAD

**Issue by buchatsky** [berhir/AspNetCore.SpaYarp#16]
Currently SpaYarp uses the root ClientUrl to check if SpaClient server is running, even when PublicPath is defined.
Formerly I used webpack to start webpack dev srver, and I specified `static: ['src']` in devServer options to direct the root request to the static src/index.html.
But now I tried to switch to Angular cli and found out that it does not allow to specify 'static' option, so SpaYarp needs to access PublicPath/PublicPath to detect the presense of spa server (index.html also needs to exist in PublicPath folder).

**Comment by berhir** [comment]
Thank you for providing a fix for it. I will make a few more tests and will publish a new version soon

**Comment by berhir** [comment]
Version 1.1 is on NuGet
