### ISSUE TITLE
SSL self signed certificate

### ISSUE THREAD

**Issue by tinquen12** [berhir/AspNetCore.SpaYarp#19]
Hello,

I have an error when the middleware tries to see if the spa is starter 

`info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot`

Is there any way to make it work ?

Thank you so much for your help 😄

**Comment by berhir** [comment]
The SPA dev server must be started with a valid/trusted certificate. The ASP.NET Core SPA templates configure the SPA dev server to create certificates using the .NET CLI. For Angular see [aspnetcore-https.js](https://github.com/berhir/AspNetCore.SpaYarp/blob/6523074e30ff8fe6bae5d7127d6abccd974dff3e/samples/AspNetAngularSpaYarp/ClientApp/aspnetcore-https.js) and the [package.json](https://github.com/berhir/AspNetCore.SpaYarp/blob/6523074e30ff8fe6bae5d7127d6abccd974dff3e/samples/AspNetAngularSpaYarp/ClientApp/package.json):
```
"prestart": "node aspnetcore-https",
"start:windows": "ng serve --port 44478 --ssl --ssl-cert %APPDATA%\\ASP.NET\\https\\%npm_package_name%.pem --ssl-key %APPDATA%\\ASP.NET\\https\\%npm_package_name%.key",
"start:default": "ng serve --port 44478 --ssl --ssl-cert $HOME/.aspnet/https/${npm_package_name}.pem --ssl-key $HOME/.aspnet/https/${npm_package_name}.key",
```

Can you access the SPA directly in the browser using HTTPS without a browser warning? If not, please fix this first. If it's working but you are still getting the error, please let me know

**Comment by tinquen12** [comment]
I'm closing the issue and opening an another one. The problem was a proxy problem. After manually desactivating the proxy usage when contacting the SPA, everything works fine. 

Sorry for the inconvenience, and thank you for your work !

**Comment by tinquen12** [comment]
In addition, maybe you could expose a setting in order to setup the httpClient used to contact the SPA (for example to configure the useProxy property). If you are ok with that I will create a PR on that subject 😄

**Comment by berhir** [comment]
Thank you for the update. What exactly did you change to make it work? I am asking because currently the http client is configured with `UseProxy = false`:
```cs
var httpClient = new HttpMessageInvoker(new SocketsHttpHandler()
        {
            UseProxy = false,
            AllowAutoRedirect = false,
            AutomaticDecompression = DecompressionMethods.None,
            UseCookies = false
        });
```

Probably it's best to create a new issue where you describe the problem and your proposed solution. A PR is very welcome :)

**Comment by tinquen12** [comment]
The problem is on the file _SpaProxyLaunchManager.cs_. I just added the `useProxy = false` to that file. 

```cs
private static HttpClient CreateHttpClient()
    {
        var httpClient = new HttpClient(new HttpClientHandler()
        {
            // It's ok for us to do this here since this service is only plugged in during development.
            ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
            UseProxy = false,
        });
        // We don't care about the returned content type as long as the server is able to answer with 2XX
        httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("*/*", 0.1));
        return httpClient;
    }
```

**Comment by berhir** [comment]
I see, thank you for the explanation. As this package is meant to be used for local development and `UseProxy = false` is already used for the proxy http client, I think we can safely change it here too.

Do you still want to create a PR?

**Comment by tinquen12** [comment]
Sure I'd be happy to !
