### ISSUE TITLE
How to implement server side rendering with Next.js 

### ISSUE THREAD

**Issue by prince272** [berhir/AspNetCore.SpaYarp#2]

**Comment by berhir** [comment]
Server-side rendering is out of the scope of this package.
Usually, you must call into the JavaScript code to render a page on the server.
Microsoft dropped the support for their SpaServices and NodeServices packages some time ago (see https://github.com/aspnet/Announcements/issues/379 and https://github.com/dotnet/aspnetcore/issues/12890)
Unfortunately, I am not aware of any good alternatives. But you can read the discussions in the linked issues and maybe one of the suggested alternatives works for you.
