### ISSUE TITLE
Update to .NET7 and Yarp 2.0.0

### ISSUE THREAD

**Issue by BenjaminVettori** [berhir/AspNetCore.SpaYarp#24]
An update to Yarp.ReverseProxy 2.0.0 would require to drop support for netcoreapp3.1 (which is out of support since December 13 2022) and .NET 5 (which is out of support since May 10, 2022) but this fixes issues with web sockets opened by the live-refresh functionality of ng serve. These Requests produce errors like 

```
An unhandled exception has occurred while executing the request.
System.NotSupportedException: Unsupported request method 'CONNECT'.  
at Yarp.ReverseProxy.Forwarder.RequestUtilities.GetHttpMethod(String method)
   at Yarp.ReverseProxy.Forwarder.HttpForwarder.CreateRequestMessageAsync(HttpContext context, String destinationPrefix, HttpTransformer transformer, ForwarderRequestConfig requestConfig, Boolean isStreamingRequest, ActivityCancellationTokenSource activityToken)
...
```

In addition, .NET7 was release November 8 2022, so it would be good to add explicit support.
If desired, I guess I can provide a pull request.

**Comment by berhir** [comment]
Dropping support for netcoreapp3.1 is fine and adding support for net7 would be great. I have no time right now, but if you can create a PR, I will try to merge it soon. Thanks!

**Comment by BenjaminVettori** [comment]
@berhir I created a pull request (#25) for the update.
I hope that I did not miss anything in the readme or samples.
Please have a look when you have time and let me know if I should change anything else.

**Comment by richardjharding** [comment]
Any update on this? - @BenjaminVettori am I right in thinking this would solve some of the issues I'm seeing with regard to vite hot module reloading and the client failing to open the was connection?

**Comment by robertlarkins** [comment]
Any chance of #25 being merged?

**Comment by berhir** [comment]
Sorry for the delay and thank you @BenjaminVettori for the PR. I merged it and published the new version to NuGet. Please verify that it works, thanks!
