### ISSUE TITLE
WriteSpaConfigurationToDisk Build Target Not Executed

### ISSUE THREAD

**Issue by DanielStout5** [berhir/AspNetCore.SpaYarp#4]
The WriteSpaConfigurationToDisk target doesn't seem to get executed. I see AssignTargetPaths being executed, but not WriteSpaConfigurationToDisk, so the spa.proxy.json file never gets generated. I've checked in `AppDomain.BaseDirectory` folder and the file isn't in there.

Here's AssignTargetPaths being executed:

```
1>Target AssignTargetPaths:
1>  Using "AssignTargetPath" task from assembly "Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
```

But WriteSpaConfigurationToDisk isn't found in the logs at all.

Instead of relying on this build task, based on values from the `csproj`, I would prefer to be able to configure the root/client URL from the C# code, e.g. in a callback to `UseSpaYarpMiddleware`. To only execute it in development mode I can simply wrap the addition of SpaYarp with either `#if DEBUG` or an `IWebHostEnvironment.IsDevelopment()` call

**Comment by berhir** [comment]
Can you share your configuration (.NET SDK Version, etc.)? Or even better a working sample so I can reproduce the issue?

It's already possible to configure the services directly in the code instead of relying on the build task.

Instead of calling `services.AddSpaYarp();` call the following lines manually:
```cs
services.AddHttpForwarder();
services.AddSingleton<SpaProxyLaunchManager>();

services.Configure<SpaDevelopmentServerOptions>(options =>
{
    options.ClientUrl = "..";
    // ...
});
```

**Comment by DanielStout5** [comment]
SDK version is 5.0.402

I would provide a working sample but I've removed SpaYarp from the project - sorry. My guess is this has something to do with how my project is set up, where the project containing Program.cs is different from the one that was adding SpaYarp into the pipeline.

**Comment by mrampazo** [comment]
I had the same issue with **SDK 6.0.100**, and I think it is a problem in nuget package configuration.
If we inspect the package with explorer, the targets file was not included:
![image](https://user-images.githubusercontent.com/66479240/145609012-51a86d23-e653-4fb3-89b1-815b11c682d9.png)

Comparing with SpaProxy, it has a build folder and target file inside the package:
![image](https://user-images.githubusercontent.com/66479240/145609110-4d121a60-5281-4db8-a158-52cddd24f1e9.png)

One possible workaround (that i am using right now) is to add the targets file content manually in your csproj file:
https://github.com/berhir/AspNetCore.SpaYarp/blob/master/src/AspNetCore.SpaYarp/build/AspNetCore.SpaYarp.targets

**Comment by berhir** [comment]
@mrampazo thanks for mentioning this issue. it happened when I added the configuration for multiple target frameworks. not sure how I missed it.
I pushed a new version that should fix the issue. can you confirm that it's working now?

**Comment by mrampazo** [comment]
@berhir yes, it's working now. I updated my package to **1.0.0-beta.4**, cleaned and rebuilt the project, and _spa.proxy.json_ file was created in _obj_ folder. Thanks for your quick reply.
