### ISSUE TITLE
[Guide] Installation

### ISSUE THREAD

**Issue by mdowais** [berhir/AspNetCore.SpaYarp#7]
I was trying to implement this, but couldn't find a good Installation Guide, but figured it out. Posting this as a issue, for people to see.

This guide assumes that you are using the default ASP.NET Core with Angular Template, but must work with basically all.

### Step 1: Add the Nuget Package

[https://www.nuget.org/packages/AspNetCore.SpaYarp](https://www.nuget.org/packages/AspNetCore.SpaYarp)

### Step 2: Remove Old SpaProxy Package

Remove the Package Microsoft.AspNetCore.SpaProxy. As it is not needed for this implementation.

Note : The default template adds a Environment Variable ASPNETCORE_HOSTINGSTARTUPASSEMBLIES": "Microsoft.AspNetCore.SpaProxy", in the launchSettings.json (Debug Properties in Visual Studio). Which has to be **removed**, so that you don't see an annoying Exception thrown that "Microsoft.AspNetCore.SpaProxy" is 404.

### Step 3: Change Project Properties

In your Project Settings (csproj) -> PropertyGroup, change the following
1. SpaProxyServerUrl to SpaClientUrl
2. SpaProxyLaunchCommand to SpaLaunchCommand

### Step 4: Add the Services and Usings in your Program.cs

// First
builder.Services.AddSpaYarp()

//Second
app.UseSpaYarp();

**Comment by berhir** [comment]
thank you @mdowais for providing this guide. I added it to the main readme file
