### ISSUE TITLE
Cannot proxy to self signed cert over https

### ISSUE THREAD

**Issue by maximilianbeller** [berhir/AspNetCore.SpaYarp#9]
When I run my app, I get the following error, which is obvious, because the self signed cert is of course not trustworthy :)

I am wondering why this error does not seem to occur for other users of SpaYarp though ... Am I missing some config?
 
```
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: UntrustedRoot
```

**Comment by berhir** [comment]
On Windows and macOS you can run `dotnet dev-certs https --trust` to trust the self-signed dev certificate. If you are on Linux, you must take some additional steps as far as I know.  
To use HTTPS, you need a valid and trusted cert.

**Comment by awtkeithlin** [comment]
No it not work. 
![](https://i.imgur.com/Wt5A2FQ.png)

**Comment by berhir** [comment]
If you want to get help, then it's not enough to write "No it not work.". Are you trying to run one of the samples or do you try to use it in your own project? What OS are you using? Have you trusted the dev certs? Can you start the SPA client app without the proxy and is it reachable via https without a warning in the browser?

As it works for most people, it's likely an issue with your configuration. If you want to get help, please provide more details.
